In [3]:
#importing numpy library
import numpy as np

In [ ]:
# np.array()
arr= np.array([1,2]) # Creates a 1D array
print(arr)
arr2=np.array([[4,6],[5,8]])   #Creates a 2D array
print(arr2)
arr3=np.array([[[5,2],[7,3]],[[1,5],[7,90]]])  #Creates a 3D array
print(arr3)

In [ ]:
# np.zeros()
arr=np.zeros((3,2))  #Creates a matrix of (3,2) dimension with all entries = 0
print(arr)

In [ ]:
# np.ones()
arr=np.ones((5,2))  #Creates a matrix of (5,2) dimension with all entries = 1
print(arr)

In [ ]:
# np.reshape()
arr=np.array([[1,2],[7,8]])
arr2=np.reshape(arr,(4,1))  # Reshapes the array to given shape unless the size remains equal
print(arr)
print(arr2)

In [ ]:
# np.concatenate()
a = np.array([[7,5], [1, 99]])
b = np.array([[84,69]])
print(np.concatenate((a,b), axis=0)) 
# Concatenates 2 arrays along the given axis provided the array dimension along the given axis match

In [ ]:
# np.mean()
arr=np.array([[4,6],[5,8]])
print(np.mean(arr))            #Prints the mean of all entries in array
print(np.mean(arr, axis=0))    #Prints the mean of entries along vertical axis
print(np.mean(arr, axis=1))    #Prints the mean of entries along horizontal axis

In [ ]:
# np.sum()
arr=np.array([[4,6],[5,8]])
print(np.sum(arr))            #Prints the sum of all entries in array
print(np.sum(arr, axis=0))    #Prints the sum of entries along vertical axis
print(np.sum(arr, axis=1))    #Prints the sum of entries along horizontal axis

In [ ]:
#np.min()
arr=np.array([[4,6],[5,8]])
print(np.min(arr))            #Prints the min of all entries in array
print(np.min(arr, axis=0))    #Prints the min of entries along vertical axis
print(np.min(arr, axis=1))    #Prints the min of entries along horizontal axis

In [ ]:
#np.max()
arr=np.array([[4,6],[5,8]])
print(np.max(arr))            #Prints the max of all entries in array
print(np.max(arr, axis=0))    #Prints the max of entries along vertical axis
print(np.max(arr, axis=1))    #Prints the max of entries along horizontal axis

In [ ]:
#np.argmax()
arr=np.array([[3,6],[6,7],[5,8]])
print(np.argmax(arr,axis=None)) #returns the index of largest entry. Since axis=None, it flattens the array 
print(np.argmax(arr,axis=0))    #returns the index of largest entry along the columns
print(np.argmax(arr,axis=1))    #returns the index of largest entry along the rows

In [ ]:
#np.argmin()
arr=np.array([[3,6],[6,7],[5,8]])
print(np.argmin(arr,axis=None)) #returns the index of smallest entry. Since axis=None, it flattens the array 
print(np.argmin(arr,axis=0))    #returns the index of smallest entry along the columns
print(np.argmin(arr,axis=1))    #returns the index of smallest entry along the rows 

In [ ]:
#np.random.rand()
arr=np.random.rand(2,2) # Creates an array with random entries of given shape. It uses lesser memory
print(arr)

In [ ]:
#np.random.randn()
arr=np.random.randn(2,2) # Creates an array with random entries from normal distribution of given shape.
print(arr)

In [27]:
#np.random.randint(low,high,size)
arr=np.random.randint(2,7,(3,4)) #creates an array with random integer entries that lie in the interval 
print(arr)

[[3 3 3 2]
 [6 2 6 4]
 [2 4 3 4]]


In [32]:
#np.dot()

    #If both a and b are 1-D arrays, it is inner product of vectors (without complex conjugation).

    #If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.

    #If either a or b is 0-D (scalar), it is equivalent to multiply and using numpy.multiply(a, b) or a * b is preferred.

    # If a is an N-D array and b is a 1-D array, it is a sum product over the last axis of a and b.

print(np.dot(6,7))

print(np.dot([2, 3], [2, 3]))

a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
print(np.dot(a, b))

42
13
[[4 1]
 [2 2]]
